version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/main.go
    goos:
      - linux
      - darwin

dockers:
  - id: my-container
    image_templates:
      - "clover0/slsa-test:{{ .Version }}"
    dockerfile: Dockerfile
    goos: linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}



release:
